import type { Metadata } from 'next'
import { roboto } from '@/shared/config'
import { Layout } from '@/widgets/layout'
import { AuthModalOpener } from '@/features/auth'
import './globals.css'

export const metadata: Metadata = {
  title: "Next Go",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={roboto.variable}>
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
