import type { Metadata } from 'next'
import { roboto } from '@/shared/assets/fonts'
import { Layout } from '@/widgets/layout'
import { Toaster } from 'sonner'
import './globals.css'

export const metadata: Metadata = {
  title: "Next Go",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={roboto.variable}>
      <body>
        <Layout>
          {children}
        </Layout>
        <Toaster position="top-left" richColors />
      </body>
    </html>
  )
}
